import{ API_KEY }from "./constants/constants";
export const originals=`discover/tv?api_key=${API_KEY}&with_networks=213`;
export const action=`discover/movie?api_key=${API_KEY}&with_genres=28`;
export const comedy=`discover/movie?api_key=${API_KEY}&with_genres=35`;
export const adventure=`discover/movie?api_key=${API_KEY}&with_genres=12`;
export const animations=`discover/movie?api_key=${API_KEY}&with_genres=16`;
export const crime=`discover/movie?api_key=${API_KEY}&with_genres=18`;
export const horror=`discover/movie?api_key=${API_KEY}&with_genres=27`;
export const romance=`discover/movie?api_key=${API_KEY}&with_genres=10749`;
export const science_fiction=`discover/movie?api_key=${API_KEY}&with_genres=878`;
export const thriller=`discover/movie?api_key=${API_KEY}&with_genres=53`;
export const music=`discover/movie?api_key=${API_KEY}&with_genres=10402`;